stages:
  - build
  - test

build:
  stage: build
  script:
    - make
    - ./gradlew build -x test
  tags:
    - shell

test:
  stage: test
  script:
    - sudo apt-get install -y apt-file
    - sudo apt-file -y update
    - apt-get install -y gcc-arm-linux-gnueabi
    - ./gradlew test -i
  tags:
    - shell

