stages:
  - build
  - test

build:
  stage: build
  script:
    - make
    - ./gradlew build -x test
  tags:
    - shell

test:
  stage: test
  script:
    - apt-get install apt-file
    - apt-file update
    - apt-get install gcc-arm-linux-gnueabi
    - ./gradlew test -i
  tags:
    - shell

