stages:
  - build
  - front_end_test
  - back_end_test

build:
  stage: build
  script:
    - make clean
    - make
    - ./gradlew build -x test
  tags:
    - wacc

front_end_test:
  stage: front_end_test
  script:
    - ./gradlew test -i --tests parser.*
    - ./gradlew test -i --tests semantics.*
  tags:
    - wacc


back_end_test:
  stage: back_end_test
  script:
    - ./gradlew test -i --tests codegen.*
  tags:
    - wacc

