package optimizers

enum class OptimizationOption(val label: String) {
    CONSTANT_FOLDING("CONSTANT FOLDING"),
    CONSTANT_PROPAGATION("CONSTANT PROPAGATION"),
    DEAD_CODE_ELIMINATION("DEAD CODE ELIMINATION"),
    PEEPHOLE_OPTIMIZATION("PEEPHOLE OPTIMIZATION")
}